---
helm_apt_key_url: https://baltocdn.com/helm/signing.asc
helm_repo: deb https://baltocdn.com/helm/stable/debian/ all main
oc_binary_url: https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
...
