---
- hosts: gp_bastion
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:

    - name: Add apt-key for Helm
      apt_key:
        url: "{{ helm_apt_key_url }}"

    - name: Add repo for Helm
      apt_repository:
        repo: "{{ helm_repo }}"
        state: present
        filename: helm-stable-debian

    - name: Update apt cache
      apt:
        update_cache: yes

  tasks:

    - name: Install required packages
      apt:
        name: 
          - git
          - python3
          - python3-pip
          - helm

    - name: Download oc client
      get_url: 
        url: "{{ oc_binary_url }}"
        dest: /tmp/oc.tar.gz
        mode: '0777'

    - name: Extract oc client
      unarchive:
        src: /tmp/oc.tar.gz
        dest: /tmp/

    - name: Copy oc binary to /usr/local/bin
      copy:
        src: /tmp/oc
        dest: /usr/local/bin/oc
        mode: "0777"
        remote_src: yes

    - name: Include ckaserer.gitlab_runner
      include_role:
        name: ckaserer.gitlab_runner
      vars:
        arch: "amd64"
...
